Models/Membership.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Loyalty.Models
{
    public class Membership
    {
        public string MembershipID { get; set; }

        public string UserID { get; set; }

        [Required(ErrorMessage = "Member ID is required")]
        public string MemberID { get; set; }

        [Required(ErrorMessage = "Loyalty Card No is required")]
        public string LoyaltyCardNo { get; set; }
        [Required(ErrorMessage = "Expiration Date is required")]
        public DateTime ExpirationDate { get; set; }
        [Required(ErrorMessage = "Member Site URL is required")]
        public string MemberSiteURL { get; set; }

        public DateTime CreateDate { get; set; }

        public DateTime LastModifiedDate { get; set; }
    }
}

Controllers/MembershipController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using System.Net;
using Microsoft.Extensions.Options;
using System.Xml.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Dynamic;
using Loyalty.Models;
using Loyalty.Repository;
using Microsoft.AspNetCore.Session;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Loyalty.Controllers
{
    public class MembershipController : Controller
    {
        MembershipRepository _membership = new MembershipRepository();
        UserRepository _user = new UserRepository();
        // GET: /<controller>/
        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserName")))
            {
                TempData["msg"] = "<script>ModalPopupsAlert('Loyalty','  Session Expired! Login Again... ');</script>";
                return RedirectToAction("Login", "User");

            }
            string userid = HttpContext.Session.GetString("UserID");
       
            return View(_membership.GetMembership(userid));
        }

        public IActionResult Create(Membership memship)
        {
            double dbsize = _user.Getdbsize();

            if (dbsize >= 4.50)
            {
                return View();
            }

            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserName")))
            {
                TempData["msg"] = "<script>ModalPopupsAlert('Loyalty','  Session Expired! Login Again... ');</script>";
                return RedirectToAction("Login", "User");

            }

            if (ModelState.IsValid && memship.MemberID != null)
            {
                string userid = HttpContext.Session.GetString("UserID");
                _membership.AddMembership(memship, userid);
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Membership memship)
        {
            double dbsize = _user.Getdbsize();

            if (dbsize >= 4.50)
            {
                return View();
            }
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserName")))
            {
                TempData["msg"] = "<script>ModalPopupsAlert('Loyalty','  Session Expired! Login Again... ');</script>";
                return RedirectToAction("Login", "User");

            }
            if (memship.MemberID != null)
            {
                _membership.UpdateMembership(memship);
                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UserName")))
            {
                TempData["msg"] = "<script>ModalPopupsAlert('Loyalty','  Session Expired! Login Again... ');</script>";
                return RedirectToAction("Login", "User");

            }
            List<Membership> _memship = _membership.GetMembershipbyID(id);
            return View(_memship[0]);
        }
    }
}

Views/Membership/Create.cshtml
@model Loyalty.Models.Membership

@{
    ViewBag.Title = "Add";

    @Html.Raw(TempData["msg"])
}


<html>
<head>
    <title>Add Membership</title>

</head>
<body>
    <!-- BEGIN PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">
                Add Membership
            </h3>
            <ul class="page-breadcrumb breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="@Url.Action("Index","Membership")">Home</a>
                    <i class="icon-angle-right"></i>
                </li>

            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN DASHBOARD STATS -->
    <div class="row">
    </div>
    <!-- END DASHBOARD STATS -->


    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet box grey">
                <div class="portlet-title">
                    <div class="caption"><i class="icon-cog"></i>This page will allow you to add a Membership.</div>
                </div>
                <div class="portlet-body form">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <div class="form-body">
                                <h3 class="form-section">Membership Information</h3>
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            @Html.TextBoxFor(model => model.MembershipID, new { @class = "hidden" })
                                            @Html.TextBoxFor(model => model.UserID, new { @class = "hidden" })
                                            @Html.Label("Member ID")
                                            @Html.TextBoxFor(model => model.MemberID, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.MemberID)
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">

                                            @Html.Label("Loyalty Card No")
                                            @Html.TextBoxFor(model => model.LoyaltyCardNo, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.LoyaltyCardNo)
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            @Html.Label("Expiration Date")

                                            @Html.TextBoxFor(model => model.ExpirationDate, new { @class = "form-control", @type = "date" })
                                            @Html.ValidationMessageFor(model => model.ExpirationDate)
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            @Html.Label("Member Site URL")

                                            @Html.TextBoxFor(model => model.MemberSiteURL, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.MemberSiteURL)
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                        <div class="form-actions right">
                            <a href="@Url.Action("Index", "Membership")" class="btn default">Cancel</a>
                            <button type="submit" value="Edit" class="btn blue"><i class="icon-ok"></i> Add</button>
                        </div>
                    }
                    <!-- END PORTLET-->
                </div>
                <div class="clearfix"></div>

            </div>
            <!-- END PAGE -->
        </div>
    </div>

</body>
</html>

Views/Membership/Edit.cshtml
@model Loyalty.Models.Membership

@{
    ViewBag.Title = "Edit";     
    @Html.Raw(TempData["msg"])
}


<html>
<head>
    <title>Update Membership</title>

</head>
<body>
    <!-- BEGIN PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">
                Update Membership
            </h3>
            <ul class="page-breadcrumb breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="@Url.Action("Index","Membership")">Home</a>
                    <i class="icon-angle-right"></i>
                </li>
          
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN DASHBOARD STATS -->
    <div class="row">
    </div>
    <!-- END DASHBOARD STATS -->


    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet box grey">
                <div class="portlet-title">
                    <div class="caption"><i class="icon-cog"></i>This page will allow you to update an Membership.</div>
                </div>
                <div class="portlet-body form">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <div class="form-body">
                                <h3 class="form-section">Membership Information</h3>
                                <div class="row">
                                    <div class="col-md-3">
                                        
                                            @Html.HiddenFor(model => model.MembershipID)
                                            @Html.HiddenFor(model => model.UserID)                                   
                                    
                                        <div class="form-group">
                                            @Html.Label("Member ID")                                   
                                            @Html.TextBoxFor(model => model.MemberID, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.MemberID)
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            @Html.Label("Loyalty Card No")                                        
                                            @Html.TextBoxFor(model => model.LoyaltyCardNo, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.LoyaltyCardNo)
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            @Html.Label("Expiration Date")                     
                                            @Html.TextBoxFor(model => model.ExpirationDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                                            @Html.ValidationMessageFor(model => model.ExpirationDate)
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            @Html.Label("Member Site URL")
                                            @Html.TextBoxFor(model => model.MemberSiteURL, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.MemberSiteURL)
                                        </div>
                                    </div>
                                </div>
                            </div>

                          
                        </div>
                        <div class="form-actions right">
                            <a href="@Url.Action("Index", "Membership")" class="btn default">Cancel</a>
                            <button type="submit" value="Edit" class="btn blue"><i class="icon-ok"></i> Update</button>
                        </div>
                    }
                    <!-- END PORTLET-->
                </div>
                <div class="clearfix"></div>

            </div>
            <!-- END PAGE -->
        </div>
    </div>
 
</body>
</html>

Views/Membership/Index.cshtml
@model IEnumerable<Loyalty.Models.Membership>
@{
    ViewBag.Title = "Update";

    @Html.Raw(TempData["msg"])
}


<!DOCTYPE html>
<html>
<head>
    <title>Index</title>
    <style type="text/css">
        /*.leftbar-heading {
            font-family: Arial,Verdana, Helvetica, sans-serif;
            font-size: 13px;
            font-style: normal;
            line-height: normal;
            font-weight: normal;
            font-variant: normal;
            text-transform: none;
        }*/
    </style>
</head>
<body>
    <!-- BEGIN PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->


            <h3 class="page-title">

                Add / Manage Membership

            </h3>

            <ul class="page-breadcrumb breadcrumb">

                <li>
                    <i class="icon-home"></i>
                    <a href="@Url.Action("Index","Membership")">
                        Home
                    </a>
                    <i class="icon-angle-right"></i>
                </li>

            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN DASHBOARD STATS -->
    <div class="row">
    </div>
    <!-- END DASHBOARD STATS -->


    <div class="clearfix"></div>
    <div class="portlet box grey">
        <div class="portlet-title">

            <div class="caption"><i class="icon-globe"></i>You can use this page to review all membership.</div>

        </div>

        <div class="portlet-body">
            <div class="table-toolbar">
                <div class="btn-group">
                    <a href="@Url.Action("Create", "Membership")" class="btn green">
                        Add Membership <i class='icon-plus'></i>
                    </a>

                </div>
            </div>
            <div id="sample_editable_1_wrapper" class="dataTables_wrapper" role="grid">
                <table class="table table-striped table-hover table-bordered dataTable" id="sample_editable_1" aria-describedby="sample_editable_1_info" style="width: 1065px;">
                    <thead>
                        <tr role="row">
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 233px;" aria-label="MemberID:activate to sort column ascending">
                                Member ID
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 240px;" aria-label="LoyaltyCardNo: activate to sort column ascending">
                                Loyalty Card No
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 240px;" aria-label="ExpirationDate: activate to sort column ascending">
                                Expiration Date
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 240px;" aria-label="MemberSiteURL: activate to sort column ascending">
                                Member Site URL
                            </th>
                            <th class="sorting-disabled" role="columnheader" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 240px;" aria-label="Actions: activate to sort column ascending">
                                Actions
                            </th>
                        </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                        @if (Model != null && Model.Count() > 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MemberID)
                                    </td>
                                    <td>

                                        @Html.DisplayFor(modelItem => item.LoyaltyCardNo)


                                    </td>
                                    <td>@Convert.ToString(string.Format("{0:MM/dd/yyyy}", item.ExpirationDate))</td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MemberSiteURL)

                                    </td>
                                    <td>
                                        <div style="padding:5px">
                                            @Html.ActionLink("Edit", "Edit", "Membership", new { id = item.MembershipID }, new { @class = "label label-sm label-success", @style = "border-radius:0px;margin-right:4px" })
                                        </div>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="5" align="center" style="color:red">
                                    No Data Found
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


            </div><div class="row"></div>
        </div>
    </div>



</body>
</html>